title: Sandun Herath
logo: /assets/logo.jpg
description: 3rd year undergraduate from the Department of Electronics and Telecommunications Engineering at University of Moratuwa. I am interested in studying Neuroscience, physiological system modelling, Machine Learning and Medical Imaging. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
