title: Sandun Herath
logo: /assets/logo.jpeg
description: I am a second year engineering undergraduate at University of Moratuwa currently studying Biomedical Engineering at the Department of Electronics and Telecommunications Engineering. I am interested in studying Neuroscience, Modelling of physiological systems, Machine Learning and and Medical Imaging. I am currently in my 4th semester.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
